### ISSUE TITLE
make not working on ubuntu 16.04 kernel 4.4.0 for sbull

### ISSUE THREAD

**Issue by chakpongchung** [duxing2007/ldd3-examples-3.x#4]
cpchung:sbull$ make
make -C /lib/modules/4.4.0-51-generic/build M=/home/cpchung/code/ldd3-examples-3.x/sbull modules
make[1]: Entering directory '/usr/src/linux-headers-4.4.0-51-generic'
  CC [M]  /home/cpchung/code/ldd3-examples-3.x/sbull/sbull.o
/home/cpchung/code/ldd3-examples-3.x/sbull/sbull.c: In function ‘sbull_make_request’:
/home/cpchung/code/ldd3-examples-3.x/sbull/sbull.c:210:2: error: too many arguments to function ‘bio_endio’
  bio_endio(bio, status);
  ^
In file included from include/linux/blkdev.h:18:0,
                 from /home/cpchung/code/ldd3-examples-3.x/sbull/sbull.c:21:
include/linux/bio.h:465:13: note: declared here
 extern void bio_endio(struct bio *);
             ^
/home/cpchung/code/ldd3-examples-3.x/sbull/sbull.c: In function ‘setup_device’:
/home/cpchung/code/ldd3-examples-3.x/sbull/sbull.c:368:38: warning: passing argument 2 of ‘blk_queue_make_request’ from incompatible pointer type [-Wincompatible-pointer-types]
   blk_queue_make_request(dev->queue, sbull_make_request);
                                      ^
In file included from /home/cpchung/code/ldd3-examples-3.x/sbull/sbull.c:21:0:
include/linux/blkdev.h:963:13: note: expected ‘blk_qc_t (*)(struct request_queue *, struct bio *) {aka unsigned int (*)(struct request_queue *, struct bio *)}’ but argument is of type ‘void (*)(struct request_queue *, struct bio *)’
 extern void blk_queue_make_request(struct request_queue *, make_request_fn *);
             ^
scripts/Makefile.build:264: recipe for target '/home/cpchung/code/ldd3-examples-3.x/sbull/sbull.o' failed
make[2]: *** [/home/cpchung/code/ldd3-examples-3.x/sbull/sbull.o] Error 1
Makefile:1418: recipe for target '_module_/home/cpchung/code/ldd3-examples-3.x/sbull' failed
make[1]: *** [_module_/home/cpchung/code/ldd3-examples-3.x/sbull] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.4.0-51-generic'
Makefile:26: recipe for target 'default' failed
make: *** [default] Error 2

**Comment by duxing2007** [comment]
fix

**Comment by duxing2007** [comment]
fix
